### ISSUE TITLE
Coding Test: React, TypeScript, CSS and Github

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#15]
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/bd8080dc-6bb5-46d2-866b-677d17db0fb3)

### Coding Test

**Task 1: Create simple TODO LIST using React and Next.js**

- [ ] Create a new React Next.js project using TypeScript.
- [ ] Create a page component called HomePage that renders a simple TodoList as shown in the animation.

What are we looking for:

- [ ] How do you generate projects?
- [ ] How do you structure your Project?
- [ ] How do you do naming conventions?
- [ ] How do you do Separation of Concern?
- [ ] Using React Design Patterns?
- [ ] How dirty and disgusting you are

**Task 2: Styling** Choose one of the following options:

_Option A: Tailwind CSS_

- [ ] Install Tailwind CSS in your Next.js project.
- [ ] Use Tailwind CSS utility classes to style the components you created in Task 1.
- [ ] Show your Creativity
- [ ] Make it responsive 

_Option B: styled-components_

- [ ] Install styled-components in your Next.js project.
- [ ] Create styled components for the components you created in Task 1.
- [ ] Show your Creativity
- [ ] Make it responsive

**What are we looking for:**

- [ ] How much CSS used
- [ ] The Responsive Design

**Task 3: Git and Version Control**

- [ ] Initialise a new Git repository in your project directory.
- [ ] Commit your code with an appropriate commit message.
- [ ] Create a new branch called feature/add-todo.
- [ ] In the HomePage component, add a footer component that displays copyright information.
- [ ] Commit your changes with an appropriate commit message.
- [ ] Push your branch to the remote repository.
- [ ] Open a new pull request to merge your feature/add-footer branch into the main branch.
- [ ] Write a descriptive pull request title and description.
- [ ] Request a code review from a team member (imaginary reviewer).
- [ ] Incorporate any feedback given by the reviewer by making additional commits.
- [ ] Merge the pull request into the main branch.
- [ ] Create a new branch called feature/update-navbar.
- [ ] In the TodoList component, add a new link to a page called Blog.
- [ ] Commit your changes with an appropriate commit message.
- [ ] Push your branch to the remote repository.
- [ ] Open a new pull request to merge your feature/update-navbar branch into the main branch.
- [ ] Write a descriptive pull request title and description.
- [ ] Request a code review from the same team member (imaginary reviewer).
- [ ] Incorporate any feedback given by the reviewer by making additional commits.
- [ ] Merge the pull request into the main branch.

**What are we looking for:**
- [ ] Can you make a branch?
- [ ] How do you make commit messages?
- [ ] Can you make a clean Pull request?
- [ ] Can you handle git rebase or git merge?
- [ ] Can you make a Pull Request that can close other multiple Issues?

**INSTRUCTIONS** for SUBMISSION

- [ ] Deadline: 24th June (2 weeks) Saturday
- [ ] MUST submit you github repository with all your code
