### ISSUE TITLE
FeedAHelp: Menu Details

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#38]
- [ ] List of ingredients required for each menu item.
- [ ] Quantity and measurements for each ingredient.
- [ ] Pricing information for individual ingredients and the overall menu.
- [ ] Display nutritional information (calories, proteins, etc.).
