### ISSUE TITLE
FeedAHelp: Admin Dashboard

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#47]
- [ ] Comprehensive backend dashboard for application management.
- [ ] Menu management (add, edit, delete menus and ingredients).
- [ ] Order tracking, management, and analytics.
- [ ] User management and support system.
- [ ] Content management for video uploads and updates.
