### ISSUE TITLE
FeedAHelp:  As a chef, I want to be able to receive menus from users and confirm my availability.

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#65]
- [ ] EPIC: Chef login roles and privileges #72 
- [ ] EPIC: Chef see the menu is details and budget calculation #73 
- [ ] EPIC: Possible to chat with chef #74
